# Generated by Django 5.0 on 2026-03-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('preserves', 'Preserves'), ('seasonal', 'Seasonal')], max_length=50),
        ),
    ]
