# Generated by Django 5.0 on 2026-03-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_allergens_product_best_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='best_before',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harvest_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='surplus_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='allergen_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='best_before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
