# Generated by Django 5.0 on 2026-04-21 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_discount_educationalcontent_delete_recipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_farm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['content_type'], name='products_ed_content_1980cd_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['producer'], name='products_ed_produce_c93c45_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['producer'], name='products_pr_produce_8653f4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available_from', 'available_to'], name='products_pr_availab_02ed1e_idx'),
        ),
    ]
