# Generated by Django 5.0 on 2026-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_delivery_method_product_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_recalled',
            field=models.BooleanField(default=False),
        ),
    ]
