# Generated by Django 5.0 on 2026-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('recalled', 'Recalled'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
    ]
