# Generated by Django 5.0 on 2026-05-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_discount_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('item', 'Per Item'), ('kg', 'Per Kg'), ('g', 'Per Gram'), ('litre', 'Per Litre'), ('dozen', 'Per Dozen'), ('pack', 'Per Pack')], default='item', max_length=10),
        ),
    ]
