# Generated by Django 5.0 on 2026-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
    ]
