# Generated by Django 5.0 on 2026-05-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_latitude_remove_user_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pro_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pro_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pro_postcode',
            new_name='postcode',
        ),
    ]
