# Generated by Django 5.0 on 2026-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='food_miles',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
