# Generated by Django 5.0 on 2026-03-21 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_date_message_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 15, 2, 33, 942646, tzinfo=datetime.timezone.utc)),
        ),
    ]
