# Generated by Django 5.0 on 2026-03-24 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 24, 20, 49, 32, 19544, tzinfo=datetime.timezone.utc)),
        ),
    ]
