# Generated by Django 5.0 on 2026-04-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
