# Generated by Django 5.0 on 2026-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
