# Generated by Django 5.0 on 2026-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='processing', max_length=20),
        ),
    ]
