# Generated by Django 5.0 on 2026-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_notification_notification_type_notification_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('order', 'Order Update'), ('alert', 'Safety Alert'), ('discount', 'Discount')], default='normal', max_length=20),
        ),
    ]
