# Generated by Django 5.0 on 2026-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='contact_name',
            field=models.CharField(default='Unknown Customer', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
