# Generated by Django 5.0 on 2026-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderitem_contact_email_orderitem_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='contact_name',
            field=models.CharField(max_length=255),
        ),
    ]
