# Generated by Django 5.0 on 2026-05-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderitem_contact_name'),
        ('products', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.educationalcontent'),
        ),
    ]
