# Generated by Django 5.0 on 2026-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_bulk_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
    ]
